API_URLS = \
    {
        "show_search": "http://api.tvmaze.com/search/shows?q={}",
        "shows_for_date":"http://api.tvmaze.com/schedule?country=US&date={}"
    }

SHOWS_WITH_NUMBERS = \
    {
        "the hundred": "The 100",
        "two broke girls": "2 Broke Girls",
        "hundred deeds for eddie mcdowd": "100 Deeds for Eddie McDowd",
        "hundred questions": "100 Questions",
        "hundred Winners": "100 Winners",
        "a thousand ways to die": "1000 Ways to Die",
        "ten things i hate about you": "10 Things I Hate About You",
        "one hundred one ways to leave a gameshow": "101 Ways to Leave a Gameshow",
        "twelve ounce mouse": "12 oz. Mouse",
        "fifteen love": "15/Love",
        "ten eight officers on duty": "10-8: Officers on Duty",
        "sixteen and pregnant": "16 and Pregnant",
        "eighteen to life": "18 to Life",
        "one hundred one dalmatians": "101 Dalmatians",
        "two d tv": "2DTV",
        "the twentieth century": "The 20th Century",
        "twenty one jump street": "21 Jump Street",
        "two hundred twenty seven": "227",
        "twenty four": "24",
        "twenty six men": "26 Men",
        "three pounds": "3 lbs",
        "three south": "3 South",
        "thirty rock": "30 Rock",
        "thirty seconds to fame": "30 Seconds to Fame",
        "thirty minutes": "31 Minutes",
        "third rock from the sun": "3rd Rock from the Sun",
        "the four thousand four hundred": "The 4400",
        "forty eight hours": "48 Hours",
        "fifty cent the money and the power": "50 Cent: The Money and the Power",
        "fifty fifty": "50/50",
        "sixty minutes": "60 Minutes",
        "six teen": "6teen",
        "the sixty four thousand dollar question": "The $64,000 Question",
        "sixty four zoo lane": "64 Zoo Lane",
        "six hundred sixty six park avenue": "666 Park Avenue",
        "seventh heaven": "7th Heaven",
        "seventy seven sunset strip": "77 Sunset Strip",
        "eight simple rules": "8 Simple Rules",
        "nine o two 1 o": "90210",
        "nine to five": "9 to 5",
        "marcos": "narcos",
    }
